export const COLOR = {
  MANDARIN: "#EF8354",
  ISLAND_SPICE: "#F5ECDF",
  GOLDEN_TAINOI: "#FBBE4B",
  WHITE: "#FFFFFF",
  BLACK: "#000000",
  CHARCOAL: "#4A4A4A",
  CELERY:"#A8C653",
  TRINIDAD: "#D24C2B",
  SILVER: "#BFC0C0",
  SILVER_OPACITY_30: "#ECEDED",
  SHADOW: "#D9D9D9"
};

export const ANSWER_TYPE = {
  MATH_INPUT: "MATH_INPUT",
  SELECT_ONE: "SELECT_ONE",
  RADIO_CHOICE: "RADIO_CHOICE",
};